### ISSUE TITLE
Great script. Here's an extension: https://github.com/kufbwxfiwy/ss-bookmarks-extended

### ISSUE THREAD

**Issue by kufbwxfiwy** [dominicwa/ss-bookmarks#2]
Great script. Here's an extension: https://github.com/kufbwxfiwy/ss-bookmarks-extended

**Comment by dominicwa** [comment]
Thanks @kufbwxfiwy. I've just updated my version again after a long period away (added a bookmarklet mainly). Feel free to mix-in anything you like back into yours (if you're still using it these days). I've added a link to your repo in the README too.
